server:
  port: 8082

spring:
  application:
    name: api-distancia
  data:
    mongodb:
      database: eats_distancia
      port: 27018
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false