server:
  port: 8081

spring:
  application:
    name: api-pagamento
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/eats_pagamento?createDatabaseIfNotExist=true
    username: pagamento
    password: pagamento123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false